"""Add missing Option columns

Revision ID: e3c896ca3b51
Revises: 
Create Date: 2025-08-26 14:11:06.122851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c896ca3b51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('options', sa.Column('iv_rank', sa.Float(), nullable=True))
    op.add_column('options', sa.Column('dte', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'dte')
    op.drop_column('options', 'iv_rank')
    # ### end Alembic commands ###
